[package]
edition = "2021"
name = "youtrack"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "plugin"

[dependencies]
base64 = "0.22"
base64-serde = "0.8"
chrono = {version = "0.4", features = ["serde"]}
extism-pdk = "1.4.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
urlencoding = "2.1"

[workspace]
