[package]
edition = "2021"
name = "memory"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "plugin"

[dependencies]
base64 = "0.21"
base64-serde = "0.8.0"
extism-pdk = "1.4.0"
rusqlite = {version = "0.34.0", features = ["bundled"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
uuid = {version = "1.16", features = ["v4", "serde"]}

[build-dependencies]
cc = "1.0"
